### ISSUE TITLE
期待您的代码和数据集

### ISSUE THREAD

**Issue by wanglijiehit** [taolusi/chisp#1]
Hi，请问一下，预计什么时候公开code和dataset呢？

**Comment by taolusi** [comment]
你好，预计一周内公布。

**Comment by taolusi** [comment]
> 
> 
> Hi，请问一下，预计什么时候公开code和dataset呢？

你好，预计一周内公布

**Comment by taolusi** [comment]
> 
> 
> > Hi，请问一下，预计什么时候公开code和dataset呢？
> 
> 你好，预计一周内公布

代码和数据已经公布，如果有任何问题，可以随时与我联系。
