### ISSUE TITLE
Will you release the Chinese dataset?

### ISSUE THREAD

**Issue by alphadl** [taolusi/chisp#2]
Hi, interesting work! As what you said in the paper ``We build a Spider dataset for Chinese'', are you planning to release the Chinese dataset?

**Comment by taolusi** [comment]
> 
> 
> Hi, interesting work! As what you said in the paper ``We build a Spider dataset for Chinese'', are you planning to release the Chinese dataset?

Our dataset has beeen released on [CSpider](https://drive.google.com/drive/folders/1SVAdUQqZ2UjjcSCSxhVXRPcXxIMu1r_C?usp=sharing) as shown in README.

**Comment by alphadl** [comment]
Thanks~
