### ISSUE TITLE
translation of table schema

### ISSUE THREAD

**Issue by slamandar** [taolusi/chisp#3]
Nice work! But why not translate table schema into Chinese as well? To simulate the real application scenario?

**Comment by taolusi** [comment]
> ?

To our knowledge, in most real applications, table names and column names in databases are in English as well, so we did not translate them into Chinese.

**Comment by taolusi** [comment]
> 
> 
> Nice work! But why not translate table schema into Chinese as well? To simulate the real application scenario?

To our knowledge, in most real applications, table names and column names in databases are in English as well, so we did not translate them into Chinese.

**Comment by slamandar** [comment]
I could understand your motivation. In real scenarios, there is also usually a mapping dictionary that explains the meaning of each column, which may alleviate even avoid the additional cross-lingual challenge. Just personal opinion.

**Comment by taolusi** [comment]
> 
> 
> I could understand your motivation. In real scenarios, there is also usually a mapping dictionary that explains the meaning of each column, which may alleviate even avoid the additional cross-lingual challenge. Just personal opinion.

In Spider dataset, this is no such mapping dictionary, so this is no explanations in our CSpidser dataset, either. The cross-lingual challenge can turn into a zero-shot learning problem if such mapping dictionary exists. We would appreciate it if you could share us with such dataset with a mapping dictionary.
