### ISSUE TITLE
char_emb in BaiduNetDisk is expired. Would you mind upload again?

### ISSUE THREAD

**Issue by ThisIsSoMe** [taolusi/chisp#8]

**Comment by taolusi** [comment]
BaiduNetDisk download link has been updated.

**Comment by ThisIsSoMe** [comment]
Thanks very much :)

**Comment by ThisIsSoMe** [comment]
> BaiduNetDisk download link has been updated.
I have downloaded the char_emb.txt, and find there are 3231 words in it. Is that right? : )

**Comment by ThisIsSoMe** [comment]
> BaiduNetDisk download link has been updated.

I have downloaded the char_emb.txt, and find there are 3231 words in it. Is that right? : )

**Comment by taolusi** [comment]
> 
> 
> > BaiduNetDisk download link has been updated.
> 
> I have downloaded the char_emb.txt, and find there are 3231 words in it. Is that right? : )

Yes, that is right.

**Comment by ThisIsSoMe** [comment]
> > > BaiduNetDisk download link has been updated.
> > 
> > 
> > I have downloaded the char_emb.txt, and find there are 3231 words in it. Is that right? : )
> 
> Yes, that is right.

Thanks very much. :)
